module.exports = {
  ENROLLMENT_ERROR: process.env.COPY_ENROLLMENT_ERROR,
  ENROLLMENT_SUCCESS: process.env.COPY_ENROLLMENT_SUCCESS,
  ALREADY_ENROLLED: process.env.COPY_ALREADY_ENROLLED,
  COMMAND_ERROR_SUFFIX: process.env.COPY_COMMAND_ERROR_SUFFIX,
  VALID_ENROLLMENTS: process.env.COPY_VALID_ENROLLMENTS,
}
